insert into reviews (movie_id, rating, review_text) values (113, 2.6, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (194, 2.3, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (112, 2.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (180, 1.8, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (136, 3.5, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (180, 4.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (130, 3.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (172, 1.6, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (111, 3.3, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (161, 1.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (194, 2.4, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (154, 2.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (127, 3.8, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (168, 2.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (130, 4.0, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (186, 3.5, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (152, 3.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (181, 2.9, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (149, 2.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (164, 3.8, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (135, 3.8, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (116, 1.6, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (133, 1.9, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (118, 3.1, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (148, 3.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (118, 4.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (141, 1.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (189, 3.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (165, 2.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (188, 1.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (167, 4.6, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (195, 4.1, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (173, 4.5, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (163, 3.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (130, 1.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (117, 4.4, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (172, 3.7, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (114, 1.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (180, 4.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (121, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (155, 1.8, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (143, 1.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (113, 1.1, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (150, 1.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (144, 3.9, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (164, 1.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (143, 2.7, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (122, 4.6, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (140, 2.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (130, 4.4, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (153, 2.4, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (175, 1.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (150, 3.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (176, 4.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (188, 2.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (190, 2.3, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (162, 2.1, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (127, 4.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (172, 1.3, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (165, 3.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (163, 4.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (189, 1.5, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (161, 2.1, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (152, 4.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (158, 1.3, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (127, 2.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (159, 1.7, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (154, 1.6, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (111, 3.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (142, 1.7, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (161, 1.5, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (148, 1.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (138, 2.1, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (125, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (118, 3.6, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (138, 4.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (166, 1.2, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (178, 3.0, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (139, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (186, 1.4, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (160, 3.8, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (117, 3.3, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (113, 2.6, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (117, 4.1, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (142, 2.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (111, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (115, 3.9, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (135, 2.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (114, 1.6, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (141, 3.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (168, 1.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (168, 4.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (122, 3.0, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (118, 3.9, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (158, 2.1, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (195, 3.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (117, 5.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (117, 3.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (194, 1.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (159, 1.0, 'A must-see!');