insert into reviews (movie_id, rating, review_text) values (3, 2.6, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (94, 2.3, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (12, 2.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (80, 1.8, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (36, 3.5, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (80, 4.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (30, 3.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (72, 1.6, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (100, 3.3, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (61, 1.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (94, 2.4, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (54, 2.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (27, 3.8, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (68, 2.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (30, 4.0, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (86, 3.5, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (52, 3.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (81, 2.9, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (49, 2.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (64, 3.8, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (35, 3.8, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (6, 1.6, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (33, 1.9, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (8, 3.1, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (48, 3.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (8, 4.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (41, 1.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (89, 3.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (65, 2.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (88, 1.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (67, 4.6, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (95, 4.1, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (73, 4.5, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (63, 3.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (30, 1.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (7, 4.4, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (72, 3.7, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (4, 1.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (80, 4.4, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (21, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (55, 1.8, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (43, 1.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (3, 1.1, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (50, 1.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (44, 3.9, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (64, 1.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (43, 2.7, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (22, 4.6, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (40, 2.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (30, 4.4, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (53, 2.4, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (75, 1.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (50, 3.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (76, 4.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (88, 2.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (90, 2.3, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (62, 2.1, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (27, 4.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (72, 1.3, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (65, 3.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (63, 4.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (89, 1.5, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (61, 2.1, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (52, 4.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (58, 1.3, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (27, 2.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (59, 1.7, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (54, 1.6, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (10, 3.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (42, 1.7, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (61, 1.5, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (48, 1.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (38, 2.1, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (25, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (18, 3.6, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (38, 4.1, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (66, 1.2, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (78, 3.0, 'Not worth watching.');
insert into reviews (movie_id, rating, review_text) values (39, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (86, 1.4, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (60, 3.8, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (7, 3.3, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (3, 2.6, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (17, 4.1, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (42, 2.5, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (100, 4.0, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (5, 3.9, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (35, 2.2, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (14, 1.6, 'Average at best.');
insert into reviews (movie_id, rating, review_text) values (41, 3.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (68, 1.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (68, 4.2, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (22, 3.0, 'Disappointing plot.');
insert into reviews (movie_id, rating, review_text) values (18, 3.9, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (58, 2.1, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (95, 3.2, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (7, 5.0, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (17, 3.7, 'A must-see!');
insert into reviews (movie_id, rating, review_text) values (94, 1.5, 'Great movie!');
insert into reviews (movie_id, rating, review_text) values (59, 1.0, 'A must-see!');